### ISSUE TITLE
统一身份认证模拟登陆有搞定吗😂

### ISSUE THREAD

**Issue by lilyomo** [starwingChen/YNU-xk_spider#3]
Rt

**Comment by starwingChen** [comment]
现在应该还能用的，身份认证自己在弹出窗口输一下就好了。
以后可能，大概，也许，应该会做一个UI界面，优化体验
_(:з」∠)_

**Comment by lilyomo** [comment]
@starwingChen 可以的
不过选课网站也可以不用selenium, 直接POST提交参数就行了.
用户密码采用 MD5 加密, 然后获取验证码的 token `http://yjsxk.ynu.edu.cn/yjsxkapp/sys/xsxkapp/login/4/vcode.do`
带着 token 就能获取到验证码, 最后识别提交一下就行

**Comment by lilyomo** [comment]
统一身份认证平台有研究吗?
https://ids.ynu.edu.cn/authserver/login

**Comment by starwingChen** [comment]
> @starwingChen 可以的
> 不过选课网站也可以不用selenium, 直接POST提交参数就行了.
> 用户密码采用 MD5 加密, 然后获取验证码的 token `http://yjsxk.ynu.edu.cn/yjsxkapp/sys/xsxkapp/login/4/vcode.do`
> 带着 token 就能获取到验证码, 最后识别提交一下就行

我一直没解决验证码的问题，图片识别有点复杂。。你说的这种是可以直接抓到验证码吗？

**Comment by lilyomo** [comment]
能抓取到验证码, 返回结果为图片, 还是涉及到识别问题.
我尝试用ocr识别, 但是效果不太理想.
